# I/O → Saturation → Bandwidth
# Target: checkoutservice (orchestrator on the critical path)
# Goal: Drop network packets on the checkout service to simulate bandwidth
#        saturation and network congestion. With 60% packet loss, downstream
#        calls to payment, shipping, email, cart, and currency will fail
#        intermittently, testing the system's tolerance for unreliable I/O.
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: contention-network-loss-checkoutservice
spec:
  engineState: active
  appinfo:
    appns: online-boutique
    applabel: app=checkoutservice
    appkind: deployment
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-network-loss
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "60"
            - name: NETWORK_PACKET_LOSS_PERCENTAGE
              value: "60"
            - name: NETWORK_INTERFACE
              value: eth0
            - name: PODS_AFFECTED_PERC
              value: "100"
            - name: CONTAINER_RUNTIME
              value: containerd
            - name: SOCKET_PATH
              value: /run/containerd/containerd.sock
        probe:
          - name: frontend-availability
            type: httpProbe
            mode: Continuous
            httpProbe/inputs:
              url: http://frontend.online-boutique.svc.cluster.local
              method:
                get:
                  criteria: ==
                  responseCode: "200"
            runProperties:
              probeTimeout: 10s
              interval: 5s
              retry: 3
