"""Reproducibility metadata for a chaosprobe run.

Captures the environment fingerprint a defender needs to argue
"reproducible on a comparable cluster" rather than just on faith:
chaosprobe + Python versions, git commit, Kubernetes server version,
node container runtime, and the CNI hint.  Everything is best-effort —
each lookup wraps its own failure and contributes ``None`` on error
rather than crashing the whole run.
"""

from __future__ import annotations

import logging
import os
import platform
import subprocess
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, TypedDict

from chaosprobe import __version__ as CHAOSPROBE_VERSION

logger = logging.getLogger(__name__)

_GIT_COMMAND_TIMEOUT = 5.0


class GitInfo(TypedDict):
    """Fixed-shape result of :func:`_git_describe`."""

    commit: Optional[str]
    shortCommit: Optional[str]
    dirty: Optional[bool]


# Paths whose uncommitted changes don't affect what the experiment *does*, so
# they must not flip the reproducibility ``dirty`` flag. The presentation is
# regenerated by every ``run`` (which would otherwise mark every post-first run
# dirty), ``results/`` holds run outputs, and ``*.md`` is prose documentation.
_DIRTY_IGNORE_SUFFIXES = (".pptx", ".md", ".html")
_DIRTY_IGNORE_SUBSTRINGS = ("results/", "/charts/")


def _affects_reproducibility(path: str) -> bool:
    """True when an uncommitted *path* reflects a change to experiment code.

    Generated artifacts (the regenerated presentation, ``results/`` outputs,
    HTML charts) and prose docs (``*.md``) don't change experiment behaviour,
    so a dirty one shouldn't claim "the recorded commit doesn't represent the
    running code". Code, scenarios, and manifests still count.
    """
    if path.endswith(_DIRTY_IGNORE_SUFFIXES):
        return False
    return not any(sub in path for sub in _DIRTY_IGNORE_SUBSTRINGS)


def _porcelain_paths(stdout: str) -> List[str]:
    """Extract file paths from ``git status --porcelain`` output.

    Handles the ``XY <path>`` form and the rename ``XY <old> -> <new>`` form
    (returning the post-rename path), stripping the two-char status code and
    any surrounding quotes git adds for unusual characters.
    """
    paths: List[str] = []
    for line in stdout.splitlines():
        if not line.strip():
            continue
        entry = line[3:] if len(line) > 3 else line.lstrip()
        if " -> " in entry:
            entry = entry.split(" -> ", 1)[1]
        paths.append(entry.strip().strip('"'))
    return paths


def _git_describe(repo_dir: Optional[str] = None) -> GitInfo:
    """Capture the current git commit + dirty flag.

    Returns ``{commit, shortCommit, dirty}`` — any field may be ``None``
    if git isn't available, the directory isn't a repo, or the command
    errors out.
    """
    cwd = repo_dir or os.getcwd()
    out: GitInfo = {"commit": None, "shortCommit": None, "dirty": None}
    try:
        commit = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=_GIT_COMMAND_TIMEOUT,
            check=False,
        )
        if commit.returncode == 0:
            out["commit"] = commit.stdout.strip() or None
            if out["commit"]:
                out["shortCommit"] = out["commit"][:12]

        status = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=_GIT_COMMAND_TIMEOUT,
            check=False,
        )
        if status.returncode == 0:
            out["dirty"] = any(_affects_reproducibility(p) for p in _porcelain_paths(status.stdout))
    except (FileNotFoundError, subprocess.TimeoutExpired):
        # git not installed or hung
        pass
    return out


def _kubernetes_server_info(core_api: Optional[Any]) -> Dict[str, Optional[str]]:
    """Best-effort K8s server version + control-plane node container
    runtime via the kubernetes API."""
    info: Dict[str, Optional[str]] = {
        "serverVersion": None,
        "containerRuntimeOnFirstNode": None,
        "firstNodeOS": None,
    }
    if core_api is None:
        return info
    try:
        from kubernetes import client as _k8s_client  # local import — runtime-only

        version_api = _k8s_client.VersionApi(api_client=core_api.api_client)
        ver = version_api.get_code()
        info["serverVersion"] = getattr(ver, "git_version", None)
    except Exception:
        logger.debug("failed to read cluster server version", exc_info=True)
    try:
        nodes = core_api.list_node(limit=1)
        if nodes.items:
            node = nodes.items[0]
            node_info = getattr(node.status, "node_info", None)
            if node_info is not None:
                info["containerRuntimeOnFirstNode"] = getattr(
                    node_info, "container_runtime_version", None
                )
                os_image = getattr(node_info, "os_image", None)
                if os_image:
                    info["firstNodeOS"] = os_image
    except Exception:
        logger.debug("failed to read first-node info", exc_info=True)
    return info


def _cni_hint(core_api: Optional[Any]) -> Optional[str]:
    """Cheap detection: look for a pod whose name starts with
    ``calico-`` / ``cilium-`` / ``kube-flannel-`` / ``weave-`` in
    ``kube-system``.  Returns the matched prefix or ``None`` if the
    listing fails or nothing matches."""
    if core_api is None:
        return None
    try:
        pods = core_api.list_namespaced_pod("kube-system", limit=200)
    except Exception:
        return None
    prefixes = ("calico-", "cilium-", "kube-flannel-", "weave-")
    for pod in pods.items:
        name = getattr(pod.metadata, "name", "") or ""
        for prefix in prefixes:
            if name.startswith(prefix):
                return prefix.rstrip("-")
    return None


def _kube_proxy_info(core_api: Optional[Any]) -> Dict[str, Any]:
    """Best-effort kube-proxy mode + conntrack settings.

    The mechanism-layer claims (conntrack flush, kube-proxy sync) are
    environment-contingent: an iptables proxier reconverges differently
    from ipvs or nftables, and the conntrack table sizing/timeouts shape
    how much flow state the kill cycle disturbs.  The kubeadm-managed
    ``kube-proxy`` ConfigMap in ``kube-system`` carries both in its
    ``config.conf`` document, so we read it from the API rather than
    needing node access.  Returns ``{mode, conntrack}`` with either field
    ``None`` when the ConfigMap is absent, unreadable, or doesn't pin it
    (an empty ``mode`` means the cluster default, which is itself not a
    pinned fact — surfaced as ``None`` so ``doctor`` can flag it).
    """
    info: Dict[str, Any] = {"mode": None, "conntrack": None}
    if core_api is None:
        return info
    try:
        import yaml  # local import — runtime-only

        cm = core_api.read_namespaced_config_map("kube-proxy", "kube-system")
        config_conf = (getattr(cm, "data", None) or {}).get("config.conf")
        if not config_conf:
            return info
        parsed = yaml.safe_load(config_conf)
        if not isinstance(parsed, dict):
            return info
        mode = parsed.get("mode")
        if isinstance(mode, str) and mode:
            info["mode"] = mode
        conntrack = parsed.get("conntrack")
        if isinstance(conntrack, dict):
            info["conntrack"] = conntrack
    except Exception:
        logger.debug("failed to read kube-proxy config", exc_info=True)
    return info


def gather_run_metadata(
    core_api: Optional[Any] = None,
    repo_dir: Optional[str] = None,
) -> Dict[str, Any]:
    """Gather a reproducibility fingerprint for the current run.

    All fields are best-effort — missing lookups become ``None`` so a
    minimal report still records what *was* known.

    Returns ``{chaosprobeVersion, pythonVersion, hostname, capturedAt,
    git: {...}, kubernetes: {...}, cniHint, kubeProxy: {...}}``.
    """
    return {
        "chaosprobeVersion": CHAOSPROBE_VERSION,
        "pythonVersion": platform.python_version(),
        "platform": platform.platform(),
        "hostname": platform.node() or None,
        "capturedAt": datetime.now(timezone.utc).isoformat(),
        "git": _git_describe(repo_dir),
        "kubernetes": _kubernetes_server_info(core_api),
        "cniHint": _cni_hint(core_api),
        "kubeProxy": _kube_proxy_info(core_api),
    }
