# Placement: Spread — Pods distributed evenly across nodes
# Combined with pod-delete on checkoutservice to measure recovery when
# services are spread (minimal resource contention, but cross-node latency).
#
# Usage:
#   1. Deploy online-boutique first:
#      uv run chaosprobe provision scenarios/online-boutique/deploy/
#   2. Apply spread placement:
#      uv run chaosprobe placement apply spread -n online-boutique
#   3. Run this experiment:
#      uv run chaosprobe run scenarios/online-boutique/placement-spread/ -o spread-results.json
#
# Hypothesis: Recovery will be fastest because the rescheduled pod has
# minimal resource competition, but probe latency may be higher due to
# inter-node networking.
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: placement-spread-pod-delete
spec:
  engineState: active
  appinfo:
    appns: online-boutique
    applabel: app=checkoutservice
    appkind: deployment
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "120"
            - name: CHAOS_INTERVAL
              value: "20"
            - name: FORCE
              value: "true"
            - name: PODS_AFFECTED_PERC
              value: "100"
        probe:
          - name: frontend-availability
            type: httpProbe
            mode: Continuous
            httpProbe/inputs:
              url: http://frontend.online-boutique.svc.cluster.local
              method:
                get:
                  criteria: ==
                  responseCode: "200"
            runProperties:
              probeTimeout: 10s
              interval: 5s
              retry: 3
