# Example: Network Chaos Scenario
# This scenario tests application resilience to network latency and packet loss.

apiVersion: chaosprobe.io/v1alpha1
kind: ChaosScenario
metadata:
  name: network-chaos-test
  description: "Test application resilience to network issues"

spec:
  infrastructure:
    namespace: chaosprobe-network
    resources:
      - name: web-app
        type: deployment
        spec:
          replicas: 2
          image: nginx:1.21
          labels:
            app: web-app
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
        anomaly:
          enabled: false

      - name: web-app-service
        type: service
        spec:
          selector:
            app: web-app
          ports:
            - port: 80
              targetPort: 80

  experiments:
    - name: network-latency-test
      type: pod-network-latency
      target:
        appLabel: "app=web-app"
        appKind: deployment
        namespace: chaosprobe-network
      parameters:
        TOTAL_CHAOS_DURATION: "60"
        NETWORK_LATENCY: "300"
        NETWORK_INTERFACE: "eth0"
        CONTAINER_RUNTIME: "containerd"
        SOCKET_PATH: "/run/k3s/containerd/containerd.sock"
      probes:
        - name: http-response-check
          type: httpProbe
          mode: Continuous
          httpProbe:
            url: "http://web-app-service.chaosprobe-network.svc.cluster.local:80"
            method:
              get:
                criteria: "=="
                responseCode: "200"
          runProperties:
            probeTimeout: "10s"
            interval: "3s"
            retry: 5

    - name: network-loss-test
      type: pod-network-loss
      target:
        appLabel: "app=web-app"
        appKind: deployment
        namespace: chaosprobe-network
      parameters:
        TOTAL_CHAOS_DURATION: "30"
        NETWORK_PACKET_LOSS_PERCENTAGE: "50"
        NETWORK_INTERFACE: "eth0"
        CONTAINER_RUNTIME: "containerd"
        SOCKET_PATH: "/run/k3s/containerd/containerd.sock"
      probes:
        - name: http-availability-check
          type: httpProbe
          mode: Continuous
          httpProbe:
            url: "http://web-app-service.chaosprobe-network.svc.cluster.local:80"
            method:
              get:
                criteria: "=="
                responseCode: "200"
          runProperties:
            probeTimeout: "10s"
            interval: "2s"
            retry: 10

  successCriteria:
    minResilienceScore: 70
    requireAllPass: false
    experimentCriteria:
      - experimentName: network-latency-test
        minProbeSuccessPercentage: 80
        expectedVerdict: Pass
      - experimentName: network-loss-test
        minProbeSuccessPercentage: 60
        expectedVerdict: Pass

  output:
    format: json
    includeRawResults: true
