# Example: Nginx Resilience Test Scenario
# This scenario provisions an nginx deployment with a single replica (no redundancy)
# and runs a pod-delete chaos experiment to test service resilience.
# With the anomaly, the single replica is deleted and the service goes down.
# Without the anomaly, 3 replicas survive pod deletion gracefully.

apiVersion: chaosprobe.io/v1alpha1
kind: ChaosScenario
metadata:
  name: nginx-resilience-test
  description: "Test nginx deployment resilience to pod failures"

spec:
  # Infrastructure to provision
  infrastructure:
    namespace: chaosprobe-test
    resources:
      - name: nginx-deployment
        type: deployment
        spec:
          replicas: 3
          image: nginx:1.21
          labels:
            app: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
        # Anomaly: reduce to 1 replica so pod deletion causes total outage
        anomaly:
          enabled: true
          type: insufficient-replicas
          description: "Single replica deployment has no redundancy, causing outage during pod deletion"

      - name: nginx-service
        type: service
        spec:
          selector:
            app: nginx
          ports:
            - port: 80
              targetPort: 80

  # Chaos experiments to run
  experiments:
    - name: pod-delete-test
      type: pod-delete
      target:
        appLabel: "app=nginx"
        appKind: deployment
        namespace: chaosprobe-test
      parameters:
        TOTAL_CHAOS_DURATION: "30"
        CHAOS_INTERVAL: "10"
        FORCE: "true"
        PODS_AFFECTED_PERC: "100"
      probes:
        - name: nginx-http-probe
          type: httpProbe
          mode: Continuous
          httpProbe:
            url: "http://nginx-service.chaosprobe-test.svc.cluster.local:80"
            method:
              get:
                criteria: "=="
                responseCode: "200"
          runProperties:
            probeTimeout: "5s"
            interval: "2s"
            retry: 3

  # Success criteria for AI evaluation
  successCriteria:
    minResilienceScore: 80
    requireAllPass: true
    experimentCriteria:
      - experimentName: pod-delete-test
        minProbeSuccessPercentage: 90
        expectedVerdict: Pass

  # Before/after comparison configuration
  comparison:
    enabled: true
    improvementCriteria:
      resilienceScoreIncrease: 10
      probeSuccessIncrease: 15

  # Output configuration
  output:
    format: json
    includeRawResults: true
